<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Insert New Picture .Ctrl</name>
   <tag></tag>
   <elementGuidId>e2fd5eb0-838e-4c3b-b0a1-a196f599e9c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menuitem-1567-textEl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert New Picture In Table...'])[1]/preceding::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>38acb15a-38af-429a-ab07-72049907e06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menuitem-1567-textEl</value>
      <webElementGuid>e8d97d11-604d-4fff-afa3-39c88d199246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>textEl</value>
      <webElementGuid>eedde599-26df-4ecd-84ef-b018b7802c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-menu-item-text x-menu-item-text-default x-menu-item-indent</value>
      <webElementGuid>28fe7f13-3e14-496a-8a11-aaf23f901033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>16b29b2f-9693-41e2-9f5c-4750d8046bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>e7266196-4a0f-420a-aff0-c977446d70d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Insert New Picture ...Ctrl+.</value>
      <webElementGuid>1e9e0613-4837-43f9-afdb-e9451737fa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuitem-1567-textEl&quot;)</value>
      <webElementGuid>86e28cff-ea89-42ca-ba3c-c35fc0e54b3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert Attachment From Library...'])[1]/following::span[1]</value>
      <webElementGuid>b85144a0-788c-4ac1-814d-1d14fa2f9764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert New Attachment...'])[1]/following::span[2]</value>
      <webElementGuid>48852a77-2973-4846-9c21-aedad745d297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Insert New Picture In Table...'])[1]/preceding::span[2]</value>
      <webElementGuid>9feea66a-d53e-4639-98c9-a380c244dbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Insert New Picture ...']/parent::*</value>
      <webElementGuid>a2eba9f3-7193-4841-b9b3-6df3e9200795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='menuitem-1567-textEl']</value>
      <webElementGuid>d6d5dc87-b171-4b0d-a625-f63f451b8725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuitem-1567-itemEl']/span</value>
      <webElementGuid>c551ae46-c9d7-42d4-8ef0-a19b5a2163cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div/div[3]/div/div/a/span</value>
      <webElementGuid>a27e0ad0-0527-4059-a195-c51e6bfcf6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'menuitem-1567-textEl' and (text() = 'Insert New Picture ...Ctrl+.' or . = 'Insert New Picture ...Ctrl+.')]</value>
      <webElementGuid>f959a5bf-4163-4211-9ab2-3ebb8e94a11e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
