name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: mac-latest
    steps:
      with:
          version: '9.5.0'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Web_Suites/WebAuto_Suite" -browserType="TestCloud" -testcloudEnvironmentId="256" -apiKey= "1be82746-1e42-405b-8841-91ee9221c2de" --config -webui.autoUpdateDrivers=true'
